server:
  port: 8085

spring:
  application:
    name: awslocalstack

  docker:
    compose:
      enabled: true
      file: compose.yaml

  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        region: eu-central-1
      credentials:
        access-key: test
        secret-key: test
      region:
        static: eu-central-1
      sqs:
        endpoint: http://localhost:4566

aws:
  bucket: mybucket
  queue: my-queue