server:
  port: 8085

spring:
  application:
    name: awslocalstack

  docker:
    compose:
      enabled: true
      file: compose.yaml

  cloud:
    aws:
      s3:
        #endpoint: http://localhost:4566 =>
        endpoint: http://s3.localhost.localstack.cloud:4566  # virtual hosted sytle URL
        region: eu-central-1
      credentials:
        access-key: test
        secret-key: test
      region:
        static: eu-central-1
      sqs:
        endpoint: http://localhost:4566

aws:
  bucket: mybucket
  queue: my-queue